name: second_ros_2
channels:
  - pytorch-lts
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2021.5.30
  - cudatoolkit=11.1.74
  - dataclasses=0.8
  - ffmpeg=4.2.2
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2022.1.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1s
  - pip=21.2.2
  - python=3.6.13
  - pytorch=1.8.2
  - readline=8.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - torchaudio=0.8.2
  - torchvision=0.9.2
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
      - cycler==0.11.0
      - decorator==4.4.2
      - fire==0.5.0
      - imageio==2.15.0
      - kiwisolver==1.3.1
      - llvmlite==0.35.0
      - matplotlib==3.3.4
      - networkx==2.5.1
      - numba==0.52.0
      - numpy==1.19.5
      - opencv-python==4.7.0.68
      - pandas==1.1.5
      - pillow==8.4.0
      - protobuf==3.19.6
      - psutil==5.9.4
      - pybind11==2.10.3
      - pykitti==0.3.1
      - pyparsing==3.0.9
      - pyquaternion==0.9.9
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pywavelets==1.1.1
      - pyyaml==6.0
      - scikit-image==0.17.2
      - scipy==1.5.4
      - seaborn==0.11.2
      - shapely==1.8.5.post1
      - tensorboardx==2.5.1
      - termcolor==1.1.0
      - tifffile==2020.9.3
